#!/bin/bash

build_and_load_gc_adapter_mod() {
    echo "Building $GC_ADAPTER_OC_MODULE"
    GC_ADAPTER_OC_BUILD_PATH=.
    cd $GC_ADAPTER_OC_BUILD_PATH
    make clean
    make
    echo "Loading $GC_ADAPTER_OC_MODULE"
    sudo insmod "$GC_ADAPTER_OC_MODULE.ko"
}

GC_ADAPTER_OC_MODULE="gcadapter_oc"

# Check if the module is loaded
if lsmod | grep -q "^$GC_ADAPTER_OC_MODULE "; then
    echo "The $GC_ADAPTER_OC_MODULE module is already loaded."
else
    echo "The $GC_ADAPTER_OC_MODULE module is not loaded."
	# if not loaded, build it and load
	build_and_load_gc_adapter_mod
fi

# RUN SLIPPI
SLIPPI=slippi.AppImage
SLIPPI_PATH=.
SLIPPI_CMD=$SLIPPI_PATH/$SLIPPI

"$SLIPPI_CMD"
