#!/bin/bash
curl -s https://api.github.com/repos/project-slippi/slippi-launcher/releases/latest | \
   	jq -r '.assets[] | select(.name | test("\\.AppImage$")) | .browser_download_url' | \
	xargs wget -O slippi.AppImage

chmod +x slippi.AppImage
